import type { Metadata } from "next";
import Link from "next/link";
import { ArrowLeft, ArrowUpRight, Github } from "lucide-react";
import { notFound } from "next/navigation";
import { SiteFooter } from "@/components/portfolio/site-footer";
import { SiteHeader } from "@/components/portfolio/site-header";
import { getProject, projects } from "@/data/projects";
export function generateStaticParams() { return projects.map(({ slug }) => ({ slug })); }
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { const project = getProject((await params).slug); return project ? { title: project.title, description: project.summary } : {}; }
export default async function ProjectPage({ params }: { params: Promise<{ slug: string }> }) { const project = getProject((await params).slug); if (!project) notFound(); return <div className="min-h-screen"><SiteHeader/><main><div className="section-shell pb-12"><Link href="/projects" className="text-link"><ArrowLeft size={16}/> All projects</Link><div className="mt-14 grid gap-10 lg:grid-cols-[1fr_auto] lg:items-end"><div><div className="mb-5 flex items-center gap-3 font-mono text-xs uppercase tracking-[.18em] text-cyan-300"><span>{project.status}</span><span className="text-slate-700">/</span><span>{project.year}</span></div><h1 className="text-5xl font-semibold tracking-[-.045em] text-white sm:text-7xl">{project.title}</h1><p className="mt-7 max-w-3xl text-xl leading-9 text-slate-400">{project.summary}</p></div><div className="flex gap-3"><a className="button-primary" href={project.liveUrl} target="_blank" rel="noreferrer">Live site <ArrowUpRight size={16}/></a><a className="button-secondary" href={project.githubUrl} target="_blank" rel="noreferrer"><Github size={17}/> Code</a></div></div></div><div className="mx-auto max-w-6xl px-6 lg:px-8"><div className="relative aspect-[16/8] border border-white/10 bg-gradient-to-br from-cyan-400/10 to-slate-950"><div className="absolute inset-[10%] border border-white/10 bg-slate-950/80 p-8"><div className="h-3 w-1/3 bg-white/10"/><div className="mt-8 grid h-2/3 grid-cols-3 gap-4"><div className="col-span-2 border border-cyan-300/10 bg-cyan-300/[.025]"/><div className="border border-white/5 bg-white/[.02]"/></div></div></div></div><section className="section-shell grid gap-12 lg:grid-cols-[1fr_2fr]"><div><p className="eyebrow">The project</p><div className="flex flex-wrap gap-2">{project.technologies.map((tech) => <span className="border border-white/10 px-3 py-1.5 text-xs text-slate-400" key={tech}>{tech}</span>)}</div></div><div><h2 className="text-3xl font-semibold text-white">Built for clarity and momentum.</h2><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-400">{project.description}</p></div></section></main><SiteFooter/></div>; }
