import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { ArrowLeft, ArrowUpRight, Github } from "lucide-react";
import { notFound } from "next/navigation";
import { ProjectsState } from "@/components/portfolio/projects-state";
import { SiteFooter } from "@/components/portfolio/site-footer";
import { SiteHeader } from "@/components/portfolio/site-header";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { getPublishedProjectBySlug } from "@/lib/projects-public";
import { getManagedProjectImagePath } from "@/lib/supabase/project-images";
export const instant = false;
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { const { project, error } = await getPublishedProjectBySlug((await params).slug); if (error) return { title: "Project", description: "Project by Aliff Najmie." }; if (!project) return { title: "Project not found", robots: { index: false, follow: false } }; return { title: project.title, description: project.summary }; }
export default async function ProjectPage({ params }: { params: Promise<{ slug: string }> }) { const { project, error } = await getPublishedProjectBySlug((await params).slug); if (error) return <div className="min-h-screen"><SiteHeader/><main className="section-shell"><ProjectsState variant="error"/></main><SiteFooter/></div>; if (!project) notFound(); const year = new Date(project.created_at).getFullYear(); return <div className="min-h-screen"><SiteHeader/><main><div className="section-shell pb-12"><Button variant="ghost" asChild className="-ml-4"><Link href="/projects"><ArrowLeft/>All projects</Link></Button><div className="mt-12 grid gap-10 lg:grid-cols-[1fr_auto] lg:items-end"><div><div className="mb-5 flex items-center gap-3 text-xs font-semibold uppercase tracking-[.18em] text-primary"><span>Case study</span><span className="text-border">/</span><span>{year}</span></div><h1 className="display-title">{project.title}</h1><p className="mt-7 max-w-3xl text-xl leading-9 text-muted-foreground">{project.summary}</p></div>{project.live_url || project.github_url ? <div className="flex flex-wrap gap-3">{project.live_url && <Button asChild><a href={project.live_url} target="_blank" rel="noreferrer">Live site <ArrowUpRight/></a></Button>}{project.github_url && <Button variant="outline" asChild><a href={project.github_url} target="_blank" rel="noreferrer"><Github/>Code</a></Button>}</div> : null}</div></div><div className="page-shell"><div className="relative aspect-[16/9] overflow-hidden rounded-lg border border-border bg-gradient-to-br from-primary/10 to-card shadow-2xl">{project.thumbnail_url ? <Image src={project.thumbnail_url} alt={`${project.title} project thumbnail`} fill priority sizes="(min-width: 1280px) 76rem, 100vw" className="object-cover" unoptimized={!getManagedProjectImagePath(project.thumbnail_url)}/> : <div className="absolute inset-[10%] rounded-md border border-border bg-background/70 p-8"><div className="h-2 w-1/3 rounded bg-muted"/><div className="mt-8 grid h-2/3 grid-cols-3 gap-4"><div className="col-span-2 rounded border border-primary/15 bg-primary/[.04]"/><div className="rounded border border-border bg-muted/30"/></div></div>}</div></div><section className="section-shell grid gap-12 lg:grid-cols-[.65fr_1.35fr]"><aside><p className="eyebrow">Technology</p>{project.technologies?.length ? <div className="flex flex-wrap gap-2">{project.technologies.map((tech) => <Badge variant="secondary" key={tech}>{tech}</Badge>)}</div> : <p className="text-sm text-muted-foreground">Technology details coming soon.</p>}</aside><article><p className="eyebrow">The project</p><h2 className="section-title">Built for clarity and momentum.</h2><p className="mt-7 max-w-3xl whitespace-pre-line text-lg leading-8 text-muted-foreground">{project.content || project.summary}</p></article></section></main><SiteFooter/></div>; }
