"use server";

import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { experienceSchema, idSchema, skillSchema, values } from "@/lib/content-schema";
import { createClient } from "@/lib/supabase/server";
import type { ContentFormState } from "@/types/content";

async function adminClient() { const supabase = await createClient(); const { data: { user }, error } = await supabase.auth.getUser(); if (error || !user) redirect("/admin/login"); return { supabase, user }; }
function failure(message: string): ContentFormState { return { errors: {}, formError: message, success: null }; }

export async function createSkill(_state: ContentFormState, formData: FormData): Promise<ContentFormState> { const { supabase, user } = await adminClient(); const parsed = skillSchema.safeParse(values(formData, ["name", "category", "proficiency", "icon", "display_order", "is_visible"])); if (!parsed.success) return { errors: parsed.error.flatten().fieldErrors, formError: null }; const { error } = await supabase.from("skills").insert(parsed.data); if (error) { console.error("Failed to create skill", { code: error.code, userId: user.id }); return failure("The skill couldn't be created. Please try again."); } revalidatePath("/"); revalidatePath("/admin/skills"); redirect("/admin/skills?success=created"); }
export async function updateSkill(id: string, _state: ContentFormState, formData: FormData): Promise<ContentFormState> { const { supabase, user } = await adminClient(); const validId = idSchema.safeParse(id); if (!validId.success) return failure("This skill couldn't be updated."); const parsed = skillSchema.safeParse(values(formData, ["name", "category", "proficiency", "icon", "display_order", "is_visible"])); if (!parsed.success) return { errors: parsed.error.flatten().fieldErrors, formError: null }; const { data, error } = await supabase.from("skills").update(parsed.data).eq("id", validId.data).select("id").maybeSingle(); if (error || !data) { console.error("Failed to update skill", { code: error?.code, userId: user.id }); return failure("The skill couldn't be updated. Please try again."); } revalidatePath("/"); revalidatePath("/admin/skills"); redirect("/admin/skills?success=updated"); }
export async function deleteSkill(id: string, _state: ContentFormState): Promise<ContentFormState> { const { supabase, user } = await adminClient(); const validId = idSchema.safeParse(id); if (!validId.success) return failure("This skill couldn't be deleted."); const { data, error } = await supabase.from("skills").delete().eq("id", validId.data).select("id").maybeSingle(); if (error || !data) { console.error("Failed to delete skill", { code: error?.code, userId: user.id }); return failure("The skill couldn't be deleted."); } revalidatePath("/"); revalidatePath("/admin/skills"); redirect("/admin/skills?success=deleted"); }
export async function toggleSkillVisibility(id: string, visible: boolean) { const { supabase } = await adminClient(); const validId = idSchema.parse(id); await supabase.from("skills").update({ is_visible: !visible }).eq("id", validId); revalidatePath("/"); revalidatePath("/admin/skills"); }

const experienceFields = ["company", "position", "location", "employment_type", "start_date", "end_date", "is_current", "summary", "achievements", "technologies", "company_url", "display_order", "is_visible"];
export async function createExperience(_state: ContentFormState, formData: FormData): Promise<ContentFormState> { const { supabase, user } = await adminClient(); const parsed = experienceSchema.safeParse(values(formData, experienceFields)); if (!parsed.success) return { errors: parsed.error.flatten().fieldErrors, formError: null }; const { error } = await supabase.from("experiences").insert(parsed.data); if (error) { console.error("Failed to create experience", { code: error.code, userId: user.id }); return failure("The experience couldn't be created. Please try again."); } revalidatePath("/"); revalidatePath("/admin/experience"); redirect("/admin/experience?success=created"); }
export async function updateExperience(id: string, _state: ContentFormState, formData: FormData): Promise<ContentFormState> { const { supabase, user } = await adminClient(); const validId = idSchema.safeParse(id); if (!validId.success) return failure("This experience couldn't be updated."); const parsed = experienceSchema.safeParse(values(formData, experienceFields)); if (!parsed.success) return { errors: parsed.error.flatten().fieldErrors, formError: null }; const { data, error } = await supabase.from("experiences").update(parsed.data).eq("id", validId.data).select("id").maybeSingle(); if (error || !data) { console.error("Failed to update experience", { code: error?.code, userId: user.id }); return failure("The experience couldn't be updated. Please try again."); } revalidatePath("/"); revalidatePath("/admin/experience"); redirect("/admin/experience?success=updated"); }
export async function deleteExperience(id: string, _state: ContentFormState): Promise<ContentFormState> { const { supabase, user } = await adminClient(); const validId = idSchema.safeParse(id); if (!validId.success) return failure("This experience couldn't be deleted."); const { data, error } = await supabase.from("experiences").delete().eq("id", validId.data).select("id").maybeSingle(); if (error || !data) { console.error("Failed to delete experience", { code: error?.code, userId: user.id }); return failure("The experience couldn't be deleted."); } revalidatePath("/"); revalidatePath("/admin/experience"); redirect("/admin/experience?success=deleted"); }
export async function toggleExperienceVisibility(id: string, visible: boolean) { const { supabase } = await adminClient(); const validId = idSchema.parse(id); await supabase.from("experiences").update({ is_visible: !visible }).eq("id", validId); revalidatePath("/"); revalidatePath("/admin/experience"); }
