import Link from "next/link";
import { ArrowRight, ArrowUpRight, Code2, Github, Linkedin, Mail, Sparkles } from "lucide-react";
import { ProjectCard } from "@/components/portfolio/project-card";
import { ProjectsState } from "@/components/portfolio/projects-state";
import { SiteFooter } from "@/components/portfolio/site-footer";
import { SiteHeader } from "@/components/portfolio/site-header";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { getPublishedProjects } from "@/lib/projects-public";

const skillGroups = [
  { index: "01", title: "Interfaces", copy: "Accessible, responsive product experiences with crisp interaction design.", skills: ["TypeScript", "React", "Next.js", "Tailwind CSS"] },
  { index: "02", title: "Systems", copy: "Reliable application foundations, data layers, and practical integrations.", skills: ["Node.js", "PostgreSQL", "REST APIs", "Supabase"] },
  { index: "03", title: "Delivery", copy: "Thoughtful engineering workflows that keep quality high and momentum steady.", skills: ["Git", "Docker", "Testing", "CI/CD"] },
];

export const instant = false;

export default async function Home() {
  const { projects, error } = await getPublishedProjects({ featured: true });
  return <div className="min-h-screen"><SiteHeader/><main>
    <section className="relative isolate overflow-hidden border-b border-border/70"><div className="soft-grid absolute inset-0 -z-20"/><div className="noise pointer-events-none absolute inset-0 -z-10"/><div className="page-shell grid min-h-[calc(100svh-4.5rem)] items-center gap-14 py-20 lg:grid-cols-[1.35fr_.65fr] lg:py-24"><div className="animate-enter"><Badge variant="outline" className="mb-8 gap-2 border-primary/25 bg-primary/[.06] px-3 py-1.5 text-primary"><span className="size-1.5 rounded-full bg-primary shadow-[0_0_12px_hsl(var(--primary))]"/>Available for select product work</Badge><h1 className="max-w-5xl text-5xl font-semibold leading-[.98] tracking-[-.055em] sm:text-7xl lg:text-[6.35rem]">Software built with clarity, craft, and intent.</h1><p className="mt-8 max-w-2xl text-lg leading-8 text-muted-foreground sm:text-xl">I&apos;m Aliff Najmie, a software developer translating complex product ideas into fast, accessible, and maintainable digital experiences.</p><div className="mt-10 flex flex-wrap gap-3"><Button size="lg" asChild><Link href="/projects">Explore selected work <ArrowRight/></Link></Button><Button size="lg" variant="outline" asChild><a href="mailto:hello@aliffnajmie.dev">Start a conversation</a></Button></div></div><Card className="animate-enter hidden overflow-hidden border-primary/15 bg-card/55 lg:block" style={{ "--delay": "180ms" } as React.CSSProperties}><CardContent className="p-0"><div className="flex items-center justify-between border-b border-border px-5 py-4"><div className="flex gap-1.5"><span className="size-2 rounded-full bg-primary/70"/><span className="size-2 rounded-full bg-muted-foreground/30"/><span className="size-2 rounded-full bg-muted-foreground/20"/></div><Code2 size={16} className="text-muted-foreground"/></div><div className="space-y-6 p-7 font-mono text-xs leading-6"><p><span className="text-primary">const</span> developer = &#123;</p><div className="space-y-2 pl-5 text-muted-foreground"><p>focus: <span className="text-foreground">&quot;useful products&quot;</span>,</p><p>approach: <span className="text-foreground">&quot;design + engineering&quot;</span>,</p><p>standard: <span className="text-foreground">&quot;care in the details&quot;</span>,</p></div><p>&#125;;</p><div className="border-t border-border pt-6 text-muted-foreground"><Sparkles className="mb-3 text-primary" size={18}/><p>Currently exploring dependable systems and thoughtful interfaces.</p></div></div></CardContent></Card></div></section>
    <section id="projects" className="section-shell"><div className="mb-12 flex flex-col gap-6 sm:flex-row sm:items-end sm:justify-between"><div><p className="eyebrow">Selected work</p><h2 className="section-title max-w-2xl">Purposeful products, carefully engineered.</h2></div><Button variant="ghost" asChild><Link href="/projects">View project archive <ArrowRight/></Link></Button></div>{error ? <ProjectsState variant="error" featured/> : projects.length ? <div className="cascade-grid grid gap-6 lg:grid-cols-2">{projects.map((project, index) => <ProjectCard key={project.slug} project={project} index={index}/>)}</div> : <ProjectsState featured/>}</section>
    <section id="skills" className="border-y border-border/70 bg-card/35"><div className="section-shell"><p className="eyebrow">Capabilities</p><div className="mb-12 grid gap-6 lg:grid-cols-2 lg:items-end"><h2 className="section-title">From product thinking to production code.</h2><p className="max-w-xl leading-7 text-muted-foreground lg:justify-self-end">A balanced toolkit for creating digital products that feel considered on the surface and remain dependable underneath.</p></div><div className="grid gap-px overflow-hidden rounded-lg border border-border bg-border lg:grid-cols-3">{skillGroups.map((group) => <div key={group.title} className="bg-background/80 p-6 sm:p-8"><span className="font-mono text-xs text-primary">{group.index}</span><h3 className="mt-8 text-xl font-semibold">{group.title}</h3><p className="mt-3 text-sm leading-6 text-muted-foreground">{group.copy}</p><div className="mt-7 flex flex-wrap gap-2">{group.skills.map((skill) => <Badge variant="secondary" key={skill}>{skill}</Badge>)}</div></div>)}</div></div></section>
    <section className="section-shell"><div className="grid gap-12 lg:grid-cols-[.8fr_1.2fr]"><div><p className="eyebrow">Experience</p><h2 className="section-title">Design sensitivity. Engineering discipline.</h2></div><div className="divide-y divide-border border-y border-border"><div className="grid gap-4 py-8 sm:grid-cols-[1fr_auto]"><div><h3 className="text-xl font-semibold">Software Developer</h3><p className="mt-3 max-w-xl leading-7 text-muted-foreground">Developing polished web applications, reusable systems, and dependable integrations for teams and growing products.</p></div><p className="font-mono text-xs text-muted-foreground">2023 — Present</p></div><div className="grid gap-4 py-8 sm:grid-cols-[1fr_auto]"><div><h3 className="text-xl font-semibold">Independent Projects</h3><p className="mt-3 max-w-xl leading-7 text-muted-foreground">Exploring product ideas end to end—from interface and architecture to deployment and iteration.</p></div><p className="font-mono text-xs text-muted-foreground">Ongoing</p></div></div></div></section>
    <section id="contact" className="page-shell pb-6 sm:pb-8"><Card className="relative overflow-hidden border-primary/20 bg-gradient-to-br from-primary/[.1] via-card to-card"><div className="soft-grid absolute inset-0 opacity-40"/><CardContent className="relative px-6 py-14 sm:px-10 sm:py-16 lg:flex lg:items-end lg:justify-between lg:px-14"><div><p className="eyebrow">Start a conversation</p><h2 className="max-w-3xl text-4xl font-semibold tracking-[-.04em] sm:text-6xl">Have a useful idea? Let&apos;s build it well.</h2></div><div className="mt-10 flex gap-2 lg:mt-0"><Button size="icon" variant="outline" asChild><a href="mailto:hello@aliffnajmie.dev" aria-label="Email Aliff"><Mail/></a></Button><Button size="icon" variant="outline" asChild><a href="https://github.com/" target="_blank" rel="noreferrer" aria-label="GitHub"><Github/></a></Button><Button size="icon" variant="outline" asChild><a href="https://linkedin.com/" target="_blank" rel="noreferrer" aria-label="LinkedIn"><Linkedin/></a></Button><Button asChild><a href="mailto:hello@aliffnajmie.dev">Get in touch <ArrowUpRight/></a></Button></div></CardContent></Card></section>
  </main><SiteFooter/></div>;
}
