import Link from "next/link";
import { ArrowRight, ArrowUpRight, Code2, Github, Linkedin, Mail, Sparkles } from "lucide-react";
import { ProjectCard } from "@/components/portfolio/project-card";
import { ProjectsState } from "@/components/portfolio/projects-state";
import { SiteFooter } from "@/components/portfolio/site-footer";
import { SiteHeader } from "@/components/portfolio/site-header";
import { SkillsSection } from "@/components/portfolio/skills-section";
import { ExperienceTimeline } from "@/components/portfolio/experience-timeline";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { getPublishedProjects } from "@/lib/projects-public";
import { getVisibleExperiences, getVisibleSkills } from "@/lib/content-public";

export const instant = false;

export default async function Home() {
  const [{ projects, error }, skills, experiences] = await Promise.all([getPublishedProjects({ featured: true }), getVisibleSkills(), getVisibleExperiences()]);
  return <div className="min-h-screen"><SiteHeader/><main>
    <section className="relative isolate overflow-hidden border-b border-border/70"><div className="soft-grid absolute inset-0 -z-20"/><div className="noise pointer-events-none absolute inset-0 -z-10"/><div className="page-shell grid min-h-[calc(100svh-4.5rem)] items-center gap-14 py-20 lg:grid-cols-[1.35fr_.65fr] lg:py-24"><div className="animate-enter"><Badge variant="outline" className="mb-8 gap-2 border-primary/25 bg-primary/[.06] px-3 py-1.5 text-primary"><span className="size-1.5 rounded-full bg-primary shadow-[0_0_12px_hsl(var(--primary))]"/>Available for select product work</Badge><h1 className="max-w-5xl text-5xl font-semibold leading-[.98] tracking-[-.055em] sm:text-7xl lg:text-[6.35rem]">Software built with clarity, craft, and intent.</h1><p className="mt-8 max-w-2xl text-lg leading-8 text-muted-foreground sm:text-xl">I&apos;m Aliff Najmie, a software developer translating complex product ideas into fast, accessible, and maintainable digital experiences.</p><div className="mt-10 flex flex-wrap gap-3"><Button size="lg" asChild><Link href="/projects">Explore selected work <ArrowRight/></Link></Button><Button size="lg" variant="outline" asChild><a href="mailto:hello@aliffnajmie.dev">Start a conversation</a></Button></div></div><Card className="animate-enter hidden overflow-hidden border-primary/15 bg-card/55 lg:block" style={{ "--delay": "180ms" } as React.CSSProperties}><CardContent className="p-0"><div className="flex items-center justify-between border-b border-border px-5 py-4"><div className="flex gap-1.5"><span className="size-2 rounded-full bg-primary/70"/><span className="size-2 rounded-full bg-muted-foreground/30"/><span className="size-2 rounded-full bg-muted-foreground/20"/></div><Code2 size={16} className="text-muted-foreground"/></div><div className="space-y-6 p-7 font-mono text-xs leading-6"><p><span className="text-primary">const</span> developer = &#123;</p><div className="space-y-2 pl-5 text-muted-foreground"><p>focus: <span className="text-foreground">&quot;useful products&quot;</span>,</p><p>approach: <span className="text-foreground">&quot;design + engineering&quot;</span>,</p><p>standard: <span className="text-foreground">&quot;care in the details&quot;</span>,</p></div><p>&#125;;</p><div className="border-t border-border pt-6 text-muted-foreground"><Sparkles className="mb-3 text-primary" size={18}/><p>Currently exploring dependable systems and thoughtful interfaces.</p></div></div></CardContent></Card></div></section>
    <section id="projects" className="section-shell"><div className="mb-12 flex flex-col gap-6 sm:flex-row sm:items-end sm:justify-between"><div><p className="eyebrow">Selected work</p><h2 className="section-title max-w-2xl">Purposeful products, carefully engineered.</h2></div><Button variant="ghost" asChild><Link href="/projects">View project archive <ArrowRight/></Link></Button></div>{error ? <ProjectsState variant="error" featured/> : projects.length ? <div className="cascade-grid grid gap-6 lg:grid-cols-2">{projects.map((project, index) => <ProjectCard key={project.slug} project={project} index={index}/>)}</div> : <ProjectsState featured/>}</section>
    <SkillsSection skills={skills.data} error={skills.error}/>
    <ExperienceTimeline experiences={experiences.data} error={experiences.error}/>
    <section id="contact" className="page-shell pb-6 sm:pb-8"><Card className="relative overflow-hidden border-primary/20 bg-gradient-to-br from-primary/[.1] via-card to-card"><div className="soft-grid absolute inset-0 opacity-40"/><CardContent className="relative px-6 py-14 sm:px-10 sm:py-16 lg:flex lg:items-end lg:justify-between lg:px-14"><div><p className="eyebrow">Start a conversation</p><h2 className="max-w-3xl text-4xl font-semibold tracking-[-.04em] sm:text-6xl">Have a useful idea? Let&apos;s build it well.</h2></div><div className="mt-10 flex gap-2 lg:mt-0"><Button size="icon" variant="outline" asChild><a href="mailto:hello@aliffnajmie.dev" aria-label="Email Aliff"><Mail/></a></Button><Button size="icon" variant="outline" asChild><a href="https://github.com/" target="_blank" rel="noreferrer" aria-label="GitHub"><Github/></a></Button><Button size="icon" variant="outline" asChild><a href="https://linkedin.com/" target="_blank" rel="noreferrer" aria-label="LinkedIn"><Linkedin/></a></Button><Button asChild><a href="mailto:hello@aliffnajmie.dev">Get in touch <ArrowUpRight/></a></Button></div></CardContent></Card></section>
  </main><SiteFooter/></div>;
}
