"use client";

import Image from "next/image";
import Link from "next/link";
import { useActionState, useEffect, useRef, useState } from "react";
import { ExternalLink, FileText, LoaderCircle } from "lucide-react";
import { saveProfile } from "@/app/admin/(dashboard)/profile/actions";
import { ContentFormField } from "@/components/admin/content-form-field";
import { Alert } from "@/components/ui/alert";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Checkbox } from "@/components/ui/checkbox";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { initialProfileFormState, profileToFormValues, type SiteProfile } from "@/types/profile";

export function ProfileForm({ profile }: { profile: SiteProfile | null }) {
  const [state, action, pending] = useActionState(saveProfile, initialProfileFormState);
  const values = profileToFormValues(profile);
  const [preview, setPreview] = useState(values.profile_image_url);
  const [removeImage, setRemoveImage] = useState(false);
  const [removeResume, setRemoveResume] = useState(false);
  const imageInput = useRef<HTMLInputElement>(null);
  const resumeInput = useRef<HTMLInputElement>(null);
  useEffect(() => () => { if (preview.startsWith("blob:")) URL.revokeObjectURL(preview); }, [preview]);

  function chooseImage(event: React.ChangeEvent<HTMLInputElement>) { const file = event.target.files?.[0]; if (!file) return; setRemoveImage(false); setPreview(URL.createObjectURL(file)); }
  function confirmRemoval(kind: "image" | "resume", checked: boolean) { if (!checked || window.confirm(`Remove the current ${kind === "image" ? "profile image" : "résumé"}? The file will be deleted when you save.`)) { if (kind === "image") { setRemoveImage(checked); if (checked) { if (imageInput.current) imageInput.current.value = ""; setPreview(""); } else setPreview(values.profile_image_url); } else { setRemoveResume(checked); if (checked && resumeInput.current) resumeInput.current.value = ""; } } }
  function confirmReplacement(event: React.FormEvent<HTMLFormElement>) { const replacingImage = Boolean(values.profile_image_url && imageInput.current?.files?.length); const replacingResume = Boolean(values.resume_url && resumeInput.current?.files?.length); if (replacingImage && !window.confirm("Replace the current profile image with the selected file?")) { event.preventDefault(); return; } if (replacingResume && !window.confirm("Replace the current résumé with the selected PDF?")) event.preventDefault(); }

  const errors = state.errors;
  return <form action={action} onSubmit={confirmReplacement} className="space-y-6" noValidate>{state.formError && <Alert variant="destructive">{state.formError}</Alert>}
    <Card><CardHeader><CardTitle>Identity and introduction</CardTitle></CardHeader><CardContent className="grid gap-6 sm:grid-cols-2"><ContentFormField name="full_name" label="Full name" required error={errors.full_name}><Input id="full_name" name="full_name" defaultValue={values.full_name} required maxLength={120} disabled={pending}/></ContentFormField><ContentFormField name="professional_title" label="Professional title" required error={errors.professional_title}><Input id="professional_title" name="professional_title" defaultValue={values.professional_title} required maxLength={160} disabled={pending}/></ContentFormField><div className="sm:col-span-2"><ContentFormField name="short_bio" label="Homepage introduction" required hint="A concise introduction shown in the hero." error={errors.short_bio}><Textarea id="short_bio" name="short_bio" rows={4} defaultValue={values.short_bio} required maxLength={500} disabled={pending}/></ContentFormField></div><div className="sm:col-span-2"><ContentFormField name="about_bio" label="About biography" hint="Use blank lines to separate readable paragraphs." error={errors.about_bio}><Textarea id="about_bio" name="about_bio" rows={9} defaultValue={values.about_bio} maxLength={5000} disabled={pending}/></ContentFormField></div></CardContent></Card>
    <Card><CardHeader><CardTitle>Contact and availability</CardTitle></CardHeader><CardContent className="grid gap-6 sm:grid-cols-2"><ContentFormField name="location" label="Location" error={errors.location}><Input id="location" name="location" defaultValue={values.location} maxLength={160} disabled={pending}/></ContentFormField><ContentFormField name="email" label="Public email" error={errors.email}><Input id="email" name="email" type="email" defaultValue={values.email} disabled={pending}/></ContentFormField><ContentFormField name="phone" label="Phone" error={errors.phone}><Input id="phone" name="phone" type="tel" defaultValue={values.phone} maxLength={40} disabled={pending}/></ContentFormField><ContentFormField name="availability_status" label="Availability status" hint="For example: Available for select work." error={errors.availability_status}><Input id="availability_status" name="availability_status" defaultValue={values.availability_status} maxLength={80} disabled={pending}/></ContentFormField><div className="sm:col-span-2"><ContentFormField name="availability_message" label="Availability message" error={errors.availability_message}><Textarea id="availability_message" name="availability_message" rows={3} defaultValue={values.availability_message} maxLength={300} disabled={pending}/></ContentFormField></div></CardContent></Card>
    <Card><CardHeader><CardTitle>Profile image and résumé</CardTitle></CardHeader><CardContent className="grid gap-8 lg:grid-cols-2"><ContentFormField name="profile_image" label="Profile image" hint="JPEG, PNG, or WebP. Maximum 5 MB." error={errors.profile_image}><Input ref={imageInput} id="profile_image" name="profile_image" type="file" accept="image/jpeg,image/png,image/webp" onChange={chooseImage} disabled={pending}/>{values.profile_image_url && <label className="mt-3 flex items-center gap-3 text-sm"><Checkbox name="remove_profile_image" checked={removeImage} onCheckedChange={(checked) => confirmRemoval("image", checked === true)} disabled={pending}/><span>Remove current image</span></label>}<div className="relative mt-4 aspect-square max-w-64 overflow-hidden rounded-lg border border-border bg-muted/30">{preview ? <Image src={preview} alt={`${values.full_name || "Profile"} preview`} fill sizes="16rem" className="object-cover" unoptimized={preview.startsWith("blob:")}/> : <div className="grid h-full place-items-center px-4 text-center text-xs text-muted-foreground">No profile image</div>}</div></ContentFormField><ContentFormField name="resume_file" label="Résumé / CV" hint="PDF only. Maximum 5 MB." error={errors.resume_file}><Input ref={resumeInput} id="resume_file" name="resume_file" type="file" accept="application/pdf" disabled={pending}/>{values.resume_url && !removeResume && <Button variant="outline" size="sm" className="mt-4" asChild><a href={values.resume_url} target="_blank" rel="noreferrer"><FileText/>View current résumé <ExternalLink/></a></Button>}{values.resume_url && <label className="mt-3 flex items-center gap-3 text-sm"><Checkbox name="remove_resume" checked={removeResume} onCheckedChange={(checked) => confirmRemoval("resume", checked === true)} disabled={pending}/><span>Remove current résumé</span></label>}</ContentFormField></CardContent></Card>
    <Card><CardHeader><CardTitle>Public links</CardTitle></CardHeader><CardContent className="grid gap-6 sm:grid-cols-2"><ContentFormField name="github_url" label="GitHub URL" error={errors.github_url}><Input id="github_url" name="github_url" type="url" defaultValue={values.github_url} placeholder="https://github.com/..." disabled={pending}/></ContentFormField><ContentFormField name="linkedin_url" label="LinkedIn URL" error={errors.linkedin_url}><Input id="linkedin_url" name="linkedin_url" type="url" defaultValue={values.linkedin_url} placeholder="https://linkedin.com/in/..." disabled={pending}/></ContentFormField><div className="sm:col-span-2"><ContentFormField name="website_url" label="Personal website URL" error={errors.website_url}><Input id="website_url" name="website_url" type="url" defaultValue={values.website_url} placeholder="https://example.com" disabled={pending}/></ContentFormField></div></CardContent></Card>
    <div className="flex flex-col-reverse gap-3 sm:flex-row sm:items-center sm:justify-between"><p className="text-xs text-muted-foreground">Uploaded files use stable paths and are replaced in place.</p><div className="flex gap-3"><Button variant="outline" asChild><Link href="/admin">Cancel</Link></Button><Button type="submit" disabled={pending}>{pending && <LoaderCircle className="animate-spin"/>}{profile ? "Save profile" : "Create profile"}</Button></div></div>
  </form>;
}
