import type { Metadata } from "next";
import Link from "next/link";
import { ArrowLeft, Mail, Reply } from "lucide-react";
import { notFound } from "next/navigation";
import { connection } from "next/server";
import { deleteMessage, updateMessage } from "../actions";
import { MessageDeleteButton } from "@/components/admin/message-delete-button";
import { MessageForm } from "@/components/admin/message-form";
import { Alert } from "@/components/ui/alert";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { messageIdSchema } from "@/lib/contact-schema";
import { createClient } from "@/lib/supabase/server";
import type { ContactMessage } from "@/types/contact";
export const metadata: Metadata = { title: "Message details", robots: { index: false, follow: false } }; export const instant = false;
const dateFormatter = new Intl.DateTimeFormat("en-MY", { dateStyle: "full", timeStyle: "short" });
export default async function MessagePage({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<{ success?: string }> }) { await connection(); const id = messageIdSchema.safeParse((await params).id); if (!id.success) notFound(); const supabase = await createClient(); const { data, error } = await supabase.from("contact_messages").select("id, name, email, subject, message, status, admin_notes, created_at, updated_at").eq("id", id.data).maybeSingle(); if (error) return <main className="p-5 sm:p-8 lg:p-10"><Alert variant="destructive">This message couldn&apos;t be loaded.</Alert></main>; if (!data) notFound(); let message = data as ContactMessage; if (message.status === "new") { const marked = await supabase.from("contact_messages").update({ status: "read" }).eq("id", message.id).eq("status", "new"); if (!marked.error) message = { ...message, status: "read" }; } const query = await searchParams; const replySubject = encodeURIComponent(`Re: ${message.subject || "Portfolio enquiry"}`); return <main className="p-5 sm:p-8 lg:p-10"><div className="mx-auto max-w-5xl"><Button variant="ghost" className="-ml-4" asChild><Link href="/admin/messages"><ArrowLeft/>Messages</Link></Button>{query.success === "updated" && <Alert className="mt-6 border-emerald-400/25 bg-emerald-400/[.06] text-emerald-200">Message updated successfully.</Alert>}<div className="mt-8 grid gap-6 lg:grid-cols-[1.35fr_.65fr]"><Card><CardHeader><div className="flex flex-wrap items-center justify-between gap-3"><Badge variant="outline">{message.status}</Badge><time className="text-xs text-muted-foreground" dateTime={message.created_at}>{dateFormatter.format(new Date(message.created_at))}</time></div><CardTitle className="pt-4 text-2xl">{message.subject || "No subject"}</CardTitle><div className="pt-2 text-sm text-muted-foreground"><p className="font-medium text-foreground">{message.name}</p><a className="mt-1 inline-flex items-center gap-2 hover:text-foreground" href={`mailto:${message.email}`}><Mail size={14}/>{message.email}</a></div></CardHeader><CardContent><div className="whitespace-pre-wrap break-words border-t border-border pt-6 leading-7 text-muted-foreground">{message.message}</div><Button className="mt-8" variant="outline" asChild><a href={`mailto:${message.email}?subject=${replySubject}`}><Reply/>Reply by email</a></Button></CardContent></Card><div className="space-y-6"><Card><CardHeader><CardTitle>Message workflow</CardTitle></CardHeader><CardContent><MessageForm message={message} action={updateMessage.bind(null, message.id)}/></CardContent></Card><Card className="border-destructive/20 bg-destructive/[.035]"><CardHeader><CardTitle>Danger zone</CardTitle></CardHeader><CardContent><MessageDeleteButton action={deleteMessage.bind(null, message.id)}/></CardContent></Card></div></div></div></main>; }
