"use client";

import { useActionState, useEffect, useRef } from "react";
import { CheckCircle2, LoaderCircle, Send } from "lucide-react";
import { submitContactMessage } from "@/app/contact-actions";
import { Alert } from "@/components/ui/alert";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { initialContactFormState } from "@/types/contact";

function Field({ name, label, error, children, optional }: { name: string; label: string; error?: string[]; children: React.ReactNode; optional?: boolean }) { return <div className="space-y-2"><div className="flex items-center justify-between gap-3"><Label htmlFor={name}>{label}</Label>{optional && <span className="text-xs text-muted-foreground">Optional</span>}</div>{children}{error?.[0] && <p id={`${name}-error`} role="alert" className="text-sm text-red-300">{error[0]}</p>}</div>; }

export function ContactForm({ startedAt }: { startedAt: number }) { const [state, action, pending] = useActionState(submitContactMessage, initialContactFormState); const form = useRef<HTMLFormElement>(null); const startedAtInput = useRef<HTMLInputElement>(null); useEffect(() => { if (state.status === "success") { form.current?.reset(); if (startedAtInput.current) startedAtInput.current.value = String(Date.now()); } }, [state.status]); return <form ref={form} action={action} className="space-y-5" noValidate><input ref={startedAtInput} type="hidden" name="started_at" defaultValue={startedAt}/><div className="absolute -left-[9999px] top-auto size-px overflow-hidden" aria-hidden="true"><Label htmlFor="website">Website</Label><Input id="website" name="website" tabIndex={-1} autoComplete="off"/></div>{state.status === "success" && <Alert className="border-emerald-400/25 bg-emerald-400/[.06] text-emerald-200"><CheckCircle2 className="mr-2 inline size-4"/>Your message has been sent. Thank you.</Alert>}{state.formError && <Alert variant="destructive">{state.formError}</Alert>}<div className="grid gap-5 sm:grid-cols-2"><Field name="name" label="Name" error={state.errors.name}><Input id="name" name="name" defaultValue={state.values.name} required minLength={2} maxLength={100} disabled={pending} aria-invalid={Boolean(state.errors.name)} aria-describedby={state.errors.name ? "name-error" : undefined}/></Field><Field name="email" label="Email" error={state.errors.email}><Input id="email" name="email" type="email" defaultValue={state.values.email} required maxLength={254} disabled={pending} aria-invalid={Boolean(state.errors.email)} aria-describedby={state.errors.email ? "email-error" : undefined}/></Field></div><Field name="subject" label="Subject" optional error={state.errors.subject}><Input id="subject" name="subject" defaultValue={state.values.subject} maxLength={150} disabled={pending} aria-invalid={Boolean(state.errors.subject)} aria-describedby={state.errors.subject ? "subject-error" : undefined}/></Field><Field name="message" label="Message" error={state.errors.message}><Textarea id="message" name="message" rows={7} defaultValue={state.values.message} required minLength={10} maxLength={3000} disabled={pending} aria-invalid={Boolean(state.errors.message)} aria-describedby={state.errors.message ? "message-error" : undefined}/></Field><Button type="submit" size="lg" className="w-full sm:w-auto" disabled={pending}>{pending ? <><LoaderCircle className="animate-spin"/>Sending...</> : <>Send message <Send/></>}</Button><p className="text-xs leading-5 text-muted-foreground">This form uses basic spam checks. Please avoid submitting the same message repeatedly.</p></form>; }
