import Image from "next/image";
import Link from "next/link";
import { ArrowRight, Download, Github, Linkedin, MapPin } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import type { SiteProfile } from "@/types/profile";

export function ProfileHero({ profile, error }: { profile: SiteProfile | null; error: boolean }) {
  if (!profile) return <section className="relative isolate overflow-hidden border-b border-border/70"><div className="soft-grid absolute inset-0 -z-20"/><div className="page-shell flex min-h-[70svh] flex-col justify-center py-20"><p className="eyebrow">Portfolio</p><h1 className="display-title max-w-4xl">Profile updates are in progress.</h1><p className="mt-6 max-w-xl leading-7 text-muted-foreground">{error ? "Profile details are temporarily unavailable." : "Profile details will appear here once configured."}</p><Button className="mt-8 w-fit" asChild><Link href="/projects">View projects <ArrowRight/></Link></Button></div></section>;
  return <section className="relative isolate overflow-hidden border-b border-border/70"><div className="soft-grid absolute inset-0 -z-20"/><div className="noise pointer-events-none absolute inset-0 -z-10"/><div className="page-shell grid min-h-[calc(100svh-4.5rem)] items-center gap-12 py-16 lg:grid-cols-[1.25fr_.75fr] lg:py-24"><div className="animate-enter">{profile.availability_status && <Badge variant="outline" className="mb-7 gap-2 border-primary/25 bg-primary/[.06] px-3 py-1.5 text-primary"><span className="size-1.5 rounded-full bg-primary shadow-[0_0_12px_hsl(var(--primary))]"/>{profile.availability_status}</Badge>}<p className="mb-4 text-sm font-semibold uppercase tracking-[.2em] text-primary">{profile.professional_title}</p><h1 className="text-5xl font-semibold leading-[.98] tracking-[-.055em] sm:text-7xl lg:text-[6.15rem]">{profile.full_name}</h1><p className="mt-8 max-w-2xl text-lg leading-8 text-muted-foreground sm:text-xl">{profile.short_bio}</p>{profile.location && <p className="mt-5 inline-flex items-center gap-2 text-sm text-muted-foreground"><MapPin size={16}/>{profile.location}</p>}<div className="mt-9 flex flex-wrap gap-3"><Button size="lg" asChild><Link href="/projects">View projects <ArrowRight/></Link></Button>{profile.resume_url && <Button size="lg" variant="outline" asChild><a href={profile.resume_url} target="_blank" rel="noreferrer"><Download/>Download résumé</a></Button>}</div><div className="mt-5 flex flex-wrap gap-2">{profile.github_url && <Button variant="ghost" size="sm" asChild><a href={profile.github_url} target="_blank" rel="noreferrer"><Github/>GitHub</a></Button>}{profile.linkedin_url && <Button variant="ghost" size="sm" asChild><a href={profile.linkedin_url} target="_blank" rel="noreferrer"><Linkedin/>LinkedIn</a></Button>}</div></div><div className="animate-enter lg:justify-self-end" style={{ "--delay": "160ms" } as React.CSSProperties}>{profile.profile_image_url ? <div className="relative mx-auto aspect-[4/5] w-full max-w-md overflow-hidden rounded-lg border border-primary/20 bg-card shadow-[0_30px_100px_-45px_hsl(var(--primary)/.4)]"><Image src={profile.profile_image_url} alt={`Portrait of ${profile.full_name}`} fill priority sizes="(min-width: 1024px) 30rem, 90vw" className="object-cover"/></div> : <Card className="w-full max-w-md border-primary/15 bg-card/55"><CardContent className="aspect-[4/5] p-8"><div className="soft-grid h-full rounded-md border border-border/70"/></CardContent></Card>}</div></div></section>;
}
