import Image from "next/image";
import Link from "next/link";
import { ArrowUpRight } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent } from "@/components/ui/card";
import { getManagedProjectImagePath } from "@/lib/supabase/project-images";
import type { Project } from "@/types/project";

function Placeholder() { return <div className="absolute inset-0 bg-gradient-to-br from-primary/15 via-card to-background"><div className="absolute inset-[12%] rounded-md border border-border bg-background/70 p-5 shadow-2xl"><div className="flex gap-1.5 border-b border-border pb-4"><span className="size-1.5 rounded-full bg-primary/70"/><span className="size-1.5 rounded-full bg-muted-foreground/40"/><span className="size-1.5 rounded-full bg-muted-foreground/20"/></div><div className="mt-5 h-2 w-2/5 rounded bg-muted"/><div className="mt-4 h-2/3 rounded border border-border bg-muted/40"/></div></div>; }

export function ProjectCard({ project, index = 0 }: { project: Project; index?: number }) { const year = new Date(project.created_at).getFullYear(); return <Card className="group animate-enter overflow-hidden transition duration-300 hover:-translate-y-1 hover:border-primary/35 hover:shadow-[0_28px_90px_-48px_hsl(var(--primary)/.3)]" style={{ "--delay": `${Math.min(index, 6) * 90}ms` } as React.CSSProperties}><Link href={`/projects/${project.slug}`} className="block"><div className="relative aspect-[16/10] overflow-hidden border-b border-border">{project.thumbnail_url ? <Image src={project.thumbnail_url} alt={`${project.title} project thumbnail`} fill sizes="(min-width: 1024px) 42vw, 100vw" className="object-cover transition duration-700 group-hover:scale-[1.035]" unoptimized={!getManagedProjectImagePath(project.thumbnail_url)}/> : <Placeholder/>}<Badge variant="secondary" className="absolute right-4 top-4 border border-border/70 bg-background/80 backdrop-blur">{year}</Badge></div><CardContent className="p-6 sm:p-7"><div className="flex items-start justify-between gap-5"><div><p className="mb-2 text-[11px] font-semibold uppercase tracking-[.18em] text-primary">Case study</p><h3 className="text-2xl font-semibold tracking-tight">{project.title}</h3></div><span className="grid size-9 shrink-0 place-items-center rounded-md border border-border text-muted-foreground transition group-hover:border-primary/40 group-hover:text-primary"><ArrowUpRight size={17}/></span></div><p className="mt-4 leading-7 text-muted-foreground">{project.summary}</p>{project.technologies?.length ? <div className="mt-6 flex flex-wrap gap-2">{project.technologies.map((tech) => <Badge key={tech} variant="outline" className="font-normal text-muted-foreground">{tech}</Badge>)}</div> : null}</CardContent></Link></Card>; }
